// resources/js/Pages/Sales/Index.jsx
import Badge from '@/Components/Badge';
import Button from '@/Components/Button';
import Card from '@/Components/Card';
import Input from '@/Components/Input';
import StatCard from '@/Components/StatCard';
import Table from '@/Components/Table';
import AppLayout from '@/Layouts/AppLayout';
import { Head, router } from '@inertiajs/react';
import { useState } from 'react';

export default function SalesIndex({ sales = [], stats = {}, filters = {} }) {
    const [fromDate, setFromDate] = useState(filters.from || '');
    const [toDate, setToDate] = useState(filters.to || '');

    const handleFilter = () => {
        router.get('/sales', { from: fromDate, to: toDate }, { preserveState: true, preserveScroll: true });
    };

    const handleClear = () => {
        setFromDate('');
        setToDate('');
        router.get('/sales', {}, { preserveState: true });
    };

    return (
        <AppLayout title="Sales">
            <Head title="Sales" />

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-4">
                <StatCard title="Sales" value={stats.count || 0} />
                <StatCard title="Revenue" value={`MVR ${(stats.total || 0).toLocaleString()}`} />
                <StatCard title="Cash" value={`MVR ${(stats.cashTotal || 0).toLocaleString()}`} />
            </div>

            <Card>
                <Card.Header>
                    <Card.Title>Sales History</Card.Title>
                    <div className="flex flex-wrap items-center gap-2">
                        <Input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} className="w-full sm:w-36" />
                        <span className="hidden text-gray-400 sm:inline">to</span>
                        <Input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} className="w-full sm:w-36" />
                        <Button onClick={handleFilter} className="w-full sm:w-auto">Filter</Button>
                        {(fromDate || toDate) && (
                            <Button variant="ghost" onClick={handleClear} className="w-full sm:w-auto">Clear</Button>
                        )}
                    </div>
                </Card.Header>

                {sales.length > 0 ? (
                    <Table>
                        <Table.Head>
                            <Table.HeadCell>Order</Table.HeadCell>
                            <Table.HeadCell>Date</Table.HeadCell>
                            <Table.HeadCell>Payment</Table.HeadCell>
                            <Table.HeadCell className="text-right">Amount</Table.HeadCell>
                        </Table.Head>
                        <Table.Body>
                            {sales.map((sale) => (
                                <Table.Row key={sale.id}>
                                    <Table.Cell className="font-medium text-gray-900">#{sale.order_number}</Table.Cell>
                                    <Table.Cell>{new Date(sale.created_at).toLocaleDateString()}</Table.Cell>
                                    <Table.Cell>
                                        <Badge variant={sale.payment_method === 'cash' ? 'success' : 'primary'}>{sale.payment_method}</Badge>
                                    </Table.Cell>
                                    <Table.Cell className="text-right font-medium text-gray-900">MVR {sale.total?.toLocaleString() || 0}</Table.Cell>
                                </Table.Row>
                            ))}
                        </Table.Body>
                    </Table>
                ) : (
                    <div className="p-8 text-center text-gray-500">No sales found</div>
                )}
            </Card>
        </AppLayout>
    );
}

// resources/js/Pages/Sales/Index.vue
<script setup>
import Badge from '@/Components/Badge.vue';
import Button from '@/Components/Button.vue';
import Card from '@/Components/Card.vue';
import Input from '@/Components/Input.vue';
import StatCard from '@/Components/StatCard.vue';
import AppLayout from '@/Layouts/AppLayout.vue';
import { Head, router } from '@inertiajs/vue3';
import { ref } from 'vue';

const props = defineProps({
    sales: {
        type: Array,
        default: () => [],
    },
    stats: {
        type: Object,
        default: () => ({}),
    },
    filters: {
        type: Object,
        default: () => ({}),
    },
});

const fromDate = ref(props.filters.from || '');
const toDate = ref(props.filters.to || '');

const handleFilter = () => {
    router.get('/sales', { from: fromDate.value, to: toDate.value }, { preserveState: true, preserveScroll: true });
};

const handleClear = () => {
    fromDate.value = '';
    toDate.value = '';
    router.get('/sales', {}, { preserveState: true });
};
</script>

<template>
    <AppLayout title="Sales">
        <Head title="Sales" />

        <div class="mb-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <StatCard title="Sales" :value="stats.count || 0" />
            <StatCard title="Revenue" :value="`MVR ${(stats.total || 0).toLocaleString()}`" />
            <StatCard title="Cash" :value="`MVR ${(stats.cashTotal || 0).toLocaleString()}`" />
        </div>

        <Card title="Sales History">
            <template #actions>
                <div class="flex flex-wrap items-center gap-2">
                    <Input v-model="fromDate" type="date" class="w-full sm:w-36" />
                    <span class="hidden text-gray-400 sm:inline">to</span>
                    <Input v-model="toDate" type="date" class="w-full sm:w-36" />
                    <Button class="w-full sm:w-auto" @click="handleFilter">Filter</Button>
                    <Button v-if="fromDate || toDate" variant="ghost" class="w-full sm:w-auto" @click="handleClear">Clear</Button>
                </div>
            </template>

            <div v-if="sales.length" class="overflow-x-auto">
                <table class="w-full text-sm text-slate-700">
                    <thead class="border-y border-emerald-100 bg-emerald-50/60">
                        <tr>
                            <th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-500">Order</th>
                            <th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-500">Date</th>
                            <th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-500">Payment</th>
                            <th class="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-slate-500">Amount</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-emerald-100/70">
                        <tr v-for="sale in sales" :key="sale.id" class="transition-colors duration-150 hover:bg-emerald-50/45">
                            <td class="px-4 py-3 font-medium text-gray-900">#{{ sale.order_number }}</td>
                            <td class="px-4 py-3">{{ new Date(sale.created_at).toLocaleDateString() }}</td>
                            <td class="px-4 py-3">
                                <Badge :variant="sale.payment_method === 'cash' ? 'success' : 'primary'">
                                    {{ sale.payment_method }}
                                </Badge>
                            </td>
                            <td class="px-4 py-3 text-right font-medium text-gray-900">
                                MVR {{ Number(sale.total || 0).toLocaleString() }}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div v-else class="p-4 text-center text-gray-500">No sales found</div>
        </Card>
    </AppLayout>
</template>
