// resources/js/Components/Card.vue
<script setup>
defineProps({
    title: {
        type: String,
        default: '',
    },
    description: {
        type: String,
        default: '',
    },
});
</script>

<template>
    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <div
            v-if="title || $slots.header || $slots.actions"
            class="flex flex-col gap-3 border-b border-slate-200 px-5 py-4 sm:flex-row sm:items-start sm:justify-between"
        >
            <div>
                <slot name="header">
                    <h3 class="text-base font-semibold text-slate-900">{{ title }}</h3>
                    <p v-if="description" class="mt-1 text-sm text-slate-500">{{ description }}</p>
                </slot>
            </div>
            <div>
                <slot name="actions" />
            </div>
        </div>
        <div class="p-5">
            <slot />
        </div>
    </section>
</template>

// resources/js/Components/Card.jsx
function Card({ children, className = '' }) {
    return (
        <div className={`rounded-lg border border-gray-200 bg-white shadow-sm ${className}`}>
            {children}
        </div>
    );
}

function CardHeader({ children, className = '' }) {
    return (
        <div className={`flex flex-col gap-3 border-b border-gray-200 px-4 py-4 sm:flex-row sm:items-center sm:justify-between ${className}`}>
            {children}
        </div>
    );
}

function CardTitle({ children }) {
    return <h3 className="text-base font-semibold text-gray-900">{children}</h3>;
}

function CardContent({ children, className = '' }) {
    return <div className={`p-4 ${className}`}>{children}</div>;
}

Card.Header = CardHeader;
Card.Title = CardTitle;
Card.Content = CardContent;

export default Card;
