// resources/js/Pages/Items/Index.vue
<script setup>
import Badge from '@/Components/Badge.vue';
import Button from '@/Components/Button.vue';
import Card from '@/Components/Card.vue';
import Input from '@/Components/Input.vue';
import Modal from '@/Components/Modal.vue';
import Select from '@/Components/Select.vue';
import AppLayout from '@/Layouts/AppLayout.vue';
import { Head, router, useForm } from '@inertiajs/vue3';
import { computed, ref } from 'vue';

const props = defineProps({
    items: {
        type: Array,
        default: () => [],
    },
    categories: {
        type: Array,
        default: () => [],
    },
});

const isModalOpen = ref(false);
const editingItem = ref(null);
const filterCategory = ref('');

const form = useForm({
    name: '',
    price: '',
    category_id: '',
});

const categoryOptions = computed(() =>
    props.categories.map((cat) => ({ value: String(cat.id), label: cat.name })),
);

const filteredItems = computed(() => {
    if (!filterCategory.value) {
        return props.items;
    }

    return props.items.filter((item) => item.category_id === Number(filterCategory.value));
});

const openCreateModal = () => {
    form.reset();
    editingItem.value = null;
    isModalOpen.value = true;
};

const openEditModal = (item) => {
    form.name = item.name;
    form.price = String(item.price);
    form.category_id = item.category_id ? String(item.category_id) : '';
    editingItem.value = item;
    isModalOpen.value = true;
};

const closeModal = () => {
    isModalOpen.value = false;
    editingItem.value = null;
    form.reset();
    form.clearErrors();
};

const submit = () => {
    if (editingItem.value) {
        form.put(`/items/${editingItem.value.id}`, { onSuccess: closeModal });
        return;
    }

    form.post('/items', { onSuccess: closeModal });
};

const handleDelete = (item) => {
    if (window.confirm('Delete this item?')) {
        router.delete(`/items/${item.id}`);
    }
};
</script>

<template>
    <AppLayout title="Items">
        <Head title="Items" />

        <Card title="Items">
            <template #actions>
                <div class="flex flex-col gap-2 sm:flex-row sm:items-center">
                    <Select
                        v-model="filterCategory"
                        :options="categoryOptions"
                        placeholder="All"
                        class="w-full sm:w-40"
                    />
                    <Button @click="openCreateModal">Add</Button>
                </div>
            </template>

            <div v-if="filteredItems.length" class="overflow-x-auto">
                <table class="w-full text-sm text-slate-700">
                    <thead class="border-y border-emerald-100 bg-emerald-50/60">
                        <tr>
                            <th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-500">Name</th>
                            <th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-500">Category</th>
                            <th class="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-slate-500">Price</th>
                            <th class="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-slate-500">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-emerald-100/70">
                        <tr v-for="item in filteredItems" :key="item.id" class="transition-colors duration-150 hover:bg-emerald-50/45">
                            <td class="px-4 py-3 font-medium text-gray-900">{{ item.name }}</td>
                            <td class="px-4 py-3">
                                <Badge>{{ item.category?.name || 'None' }}</Badge>
                            </td>
                            <td class="px-4 py-3 text-right font-medium text-gray-900">MVR {{ item.price }}</td>
                            <td class="px-4 py-3">
                                <div class="flex justify-end gap-2">
                                    <Button variant="ghost" size="sm" @click="openEditModal(item)">Edit</Button>
                                    <Button variant="ghost" size="sm" class="text-rose-600" @click="handleDelete(item)">Delete</Button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div v-else class="p-4 text-center text-gray-500">No items</div>
        </Card>

        <Modal :show="isModalOpen" :title="editingItem ? 'Edit Item' : 'Add Item'" @close="closeModal">
            <form @submit.prevent="submit">
                <div class="space-y-4">
                    <Input v-model="form.name" label="Name" placeholder="Item name" :error="form.errors.name" autofocus />
                    <Input v-model="form.price" label="Price" type="number" placeholder="0" :error="form.errors.price" />
                    <Select
                        v-model="form.category_id"
                        label="Category"
                        :options="categoryOptions"
                        placeholder="Select"
                        :error="form.errors.category_id"
                    />
                </div>

                <div class="mt-4 flex justify-end gap-2 border-t border-gray-200 pt-4">
                    <Button type="button" variant="secondary" @click="closeModal">Cancel</Button>
                    <Button type="submit" :disabled="form.processing">
                        {{ form.processing ? 'Saving...' : 'Save' }}
                    </Button>
                </div>
            </form>
        </Modal>
    </AppLayout>
</template>

// resources/js/Pages/Items/Index.jsx
import Badge from '@/Components/Badge';
import Button from '@/Components/Button';
import Card from '@/Components/Card';
import Input from '@/Components/Input';
import Modal from '@/Components/Modal';
import Select from '@/Components/Select';
import Table from '@/Components/Table';
import AppLayout from '@/Layouts/AppLayout';
import { Head, router, useForm } from '@inertiajs/react';
import { useState } from 'react';

export default function ItemsIndex({ items = [], categories = [] }) {
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingItem, setEditingItem] = useState(null);
    const [filterCategory, setFilterCategory] = useState('');

    const { data, setData, post, put, processing, errors, reset } = useForm({
        name: '',
        price: '',
        category_id: '',
    });

    const filteredItems = filterCategory
        ? items.filter(item => item.category_id === parseInt(filterCategory))
        : items;

    const openCreateModal = () => {
        reset();
        setEditingItem(null);
        setIsModalOpen(true);
    };

    const openEditModal = (item) => {
        setData({
            name: item.name,
            price: item.price.toString(),
            category_id: item.category_id?.toString() || '',
        });
        setEditingItem(item);
        setIsModalOpen(true);
    };

    const closeModal = () => {
        setIsModalOpen(false);
        setEditingItem(null);
        reset();
    };

    const submit = (e) => {
        e.preventDefault();
        if (editingItem) {
            put(`/items/${editingItem.id}`, { onSuccess: closeModal });
        } else {
            post('/items', { onSuccess: closeModal });
        }
    };

    const handleDelete = (item) => {
        if (confirm('Delete this item?')) {
            router.delete(`/items/${item.id}`);
        }
    };

    return (
        <AppLayout title="Items">
            <Head title="Items" />
            <Card>
                <Card.Header>
                    <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-3">
                        <Card.Title>Items</Card.Title>
                        <Select options={categories.map(cat => ({ value: cat.id, label: cat.name }))} placeholder="All" value={filterCategory} onChange={(e) => setFilterCategory(e.target.value)} className="w-full sm:w-32" />
                    </div>
                    <Button onClick={openCreateModal}>Add</Button>
                </Card.Header>
                {filteredItems.length > 0 ? (
                    <Table>
                        <Table.Head>
                            <Table.HeadCell>Name</Table.HeadCell>
                            <Table.HeadCell>Category</Table.HeadCell>
                            <Table.HeadCell className="text-right">Price</Table.HeadCell>
                            <Table.HeadCell></Table.HeadCell>
                        </Table.Head>
                        <Table.Body>
                            {filteredItems.map((item) => (
                                <Table.Row key={item.id}>
                                    <Table.Cell className="font-medium text-gray-900">{item.name}</Table.Cell>
                                    <Table.Cell><Badge>{item.category?.name || 'None'}</Badge></Table.Cell>
                                    <Table.Cell className="text-right font-medium text-gray-900">MVR {item.price}</Table.Cell>
                                    <Table.Cell>
                                        <div className="flex justify-end gap-2">
                                            <Button variant="ghost" size="sm" onClick={() => openEditModal(item)}>Edit</Button>
                                            <Button variant="ghost" size="sm" className="text-rose-600" onClick={() => handleDelete(item)}>Delete</Button>
                                        </div>
                                    </Table.Cell>
                                </Table.Row>
                            ))}
                        </Table.Body>
                    </Table>
                ) : (<div className="p-8 text-center text-gray-500">No items</div>)}
            </Card>
            <Modal isOpen={isModalOpen} onClose={closeModal} title={editingItem ? 'Edit Item' : 'Add Item'}>
                <form onSubmit={submit}>
                    <div className="space-y-4">
                        <Input label="Name" placeholder="Item name" value={data.name} onChange={(e) => setData('name', e.target.value)} error={errors.name} autoFocus />
                        <Input label="Price" type="number" placeholder="0" value={data.price} onChange={(e) => setData('price', e.target.value)} error={errors.price} />
                        <Select label="Category" options={categories.map(cat => ({ value: cat.id, label: cat.name }))} placeholder="Select" value={data.category_id} onChange={(e) => setData('category_id', e.target.value)} error={errors.category_id} />
                    </div>
                    <Modal.Footer>
                        <Button variant="secondary" type="button" onClick={closeModal}>Cancel</Button>
                        <Button type="submit" disabled={processing}>{processing ? 'Saving...' : 'Save'}</Button>
                    </Modal.Footer>
                </form>
            </Modal>
        </AppLayout>
    );
}
