// resources/js/Pages/Auth/Login.vue
<script setup>
import Button from '@/Components/Button.vue';
import Input from '@/Components/Input.vue';
import GuestLayout from '@/Layouts/GuestLayout.vue';
import { Head, useForm } from '@inertiajs/vue3';

const form = useForm({
    email: '',
    password: '',
});

const submit = () => {
    form.post('/login');
};
</script>

<template>
    <GuestLayout>
        <Head title="Login" />

        <h2 class="mb-4 text-lg font-medium text-gray-900">Sign in</h2>

        <form class="space-y-4" @submit.prevent="submit">
            <Input
                v-model="form.email"
                label="Email"
                type="email"
                placeholder="your@email.com"
                :error="form.errors.email"
            />

            <Input
                v-model="form.password"
                label="Password"
                type="password"
                placeholder="••••••••"
                :error="form.errors.password"
            />

            <Button type="submit" class="w-full" :disabled="form.processing">
                {{ form.processing ? 'Signing in...' : 'Sign in' }}
            </Button>
        </form>
    </GuestLayout>
</template>

// resources/js/Pages/Auth/Login.jsx
import Button from '@/Components/Button';
import Input from '@/Components/Input';
import GuestLayout from '@/Layouts/GuestLayout';
import { Head, useForm } from '@inertiajs/react';

export default function Login() {
    const { data, setData, post, processing, errors } = useForm({
        email: '',
        password: '',
    });

    const submit = (e) => {
        e.preventDefault();
        post('/login');
    };

    return (
        <GuestLayout>
            <Head title="Login" />

            <h2 className="text-lg font-medium text-gray-900 mb-4">Sign in</h2>

            <form onSubmit={submit} className="space-y-4">
                <Input
                    label="Email"
                    type="email"
                    placeholder="your@email.com"
                    value={data.email}
                    onChange={(e) => setData('email', e.target.value)}
                    error={errors.email}
                />

                <Input
                    label="Password"
                    type="password"
                    placeholder="••••••••"
                    value={data.password}
                    onChange={(e) => setData('password', e.target.value)}
                    error={errors.password}
                />

                <Button type="submit" className="w-full" disabled={processing}>
                    {processing ? 'Signing in...' : 'Sign in'}
                </Button>
            </form>
        </GuestLayout>
    );
}
